name: puro
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0-144.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  args: ^2.3.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  protobuf: ^2.1.0
  file: ^6.1.4
  typed_data: ^1.3.1
  clock: ^1.1.1
  neoansi: ^0.3.2+1
  process: ^4.2.4
  http: ^0.13.5
  async: ^2.9.0
  pub_semver: ^2.1.1
  yaml: ^3.1.1
  yaml_edit: ^2.0.3
  stack_trace: ^1.10.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  lints: ^2.0.0
  test: ^1.16.0