site_name: Puro
site_url: https://puro.dev
nav:
    - Home:
      - index.md
    - Reference:
      - reference/reference.md
      - reference/changelog.md
    - 'pub.dev': https://pub.dev/packages/puro
    - 'Discord': https://discord.com/invite/N7Yshp4
theme:
  name: material
  custom_dir: overrides
  logo: assets/puro_icon_small.png
  favicon: assets/puro_icon_small.png
  palette:
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - content.code.annotate
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
  analytics:
    provider: google
    property: G-245TJ8036B'
  social:
    - icon: fontawesome/solid/heart
      link: https://tst.sh
repo_url: https://github.com/PixelToast/puro
extra_css:
  - stylesheets/extra.css